"""Add reference field to MaintenanceRecord

Revision ID: da95e52995e5
Revises: 
Create Date: 2025-04-02 16:27:58.193382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da95e52995e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_record', sa.Column('reference', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_record', 'reference')
    # ### end Alembic commands ###
