"""Add OwnershipChange model

Revision ID: dd644075e091
Revises: da95e52995e5
Create Date: 2025-04-02 16:43:50.528625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd644075e091'
down_revision = 'da95e52995e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownership_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('previous_owner', sa.String(length=100), nullable=True),
    sa.Column('new_owner', sa.String(length=100), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ownership_change')
    # ### end Alembic commands ###
